networks:
  laravel:
    driver: bridge

services:
  front:
    build: 
      context: ./front/
    container_name: front_react
    ports:
      - "80:80"
    depends_on:
      - php_fpm
      - nginx
    restart: always

volumes:
  pgdata:
