name: DEPLOY  BACKEND

on:
  pull_request:
    branches:
      - dev
    types:
      - closed


  workflow_dispatch:

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files With Repository
        uses: actions/checkout@v2
        
      - name: Deploy Only 'back' Folder to VPS
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_VPS }}
          REMOTE_HOST: ${{ secrets.IP_VPS }}
          REMOTE_USER: ${{ secrets.USER_VPS }}
          REMOTE_PORT: 22
          TARGET: "./code/ifsp/lds/back"
          ARGS: "-avz"
          SOURCE: "back/"
      
      - name: Run Docker commands
        run: |
          cd ~/.ssh && echo "${{ secrets.SSH_PRIVATE_VPS }}" > oracle_ssh.pem && chmod 600 oracle_ssh.pem &&
          ssh -p oracle_ssh.pem ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} << 'EOF'
            cd ${{ env.TARGET }}
            docker-compose down
            docker-compose up -d --build
          EOF
        env:
          REMOTE_HOST: ${{ secrets.IP_VPS }}
          REMOTE_USER: ${{ secrets.USER_VPS }}
          TARGET: "./code/ifsp/lds/back"
          ARGS: "-avz"
          SOURCE: "back/"
      
